-- ========== FINDING OBJECT LOCK ==========-
SELECT B.SCHEMANAME, C.OWNER, COUNT(C.OBJECT_NAME), C.OBJECT_TYPE, B.SID, B.SERIAL#, B.STATUS, B.OSUSER, B.MACHINE, B.SECONDS_IN_WAIT
FROM V$LOCKED_OBJECT A, V$SESSION B, DBA_OBJECTS C
WHERE B.SID = A.SESSION_ID
AND A.OBJECT_ID = C.OBJECT_ID
AND B.USERNAME LIKE '%'
GROUP BY B.SCHEMANAME, C.OWNER, C.OBJECT_TYPE, B.SID, B.SERIAL#, B.STATUS, B.OSUSER, B.MACHINE, B.SECONDS_IN_WAIT
ORDER BY B.SECONDS_IN_WAIT DESC;

-- ============= FINDING SESSION LOCK 3 ==============--
SELECT
(SELECT USERNAME FROM V$SESSION WHERE SID=A.SID) BLOCKER, A.SID "BLOCKER_ID", (SELECT SERIAL# FROM V$SESSION WHERE SID=A.SID) "BLOCKER_SERIAL",
' IS BLOCKING ' AS ACTION_TYPE,
(SELECT USERNAME FROM V$SESSION WHERE SID=B.SID) BLOCKEE, B.SID "BLOCKEE_ID", (SELECT SERIAL# FROM V$SESSION WHERE SID=B.SID) "BLOCKEE_SERIAL"
FROM V$LOCK A, V$LOCK B
WHERE A.BLOCK = 1 AND B.REQUEST > 0 AND A.ID1=B.ID1 AND A.ID2=B.ID2;

ALTER SYSTEM KILL SESSION '472,44728' IMMEDIATE;