-- ========== FINDING WAITING SESSIONS ==========-
SELECT 
    S.SID, S.SERIAL#, S.USERNAME, S.STATUS, S.SCHEMANAME, S.MODULE, S.OSUSER, S.PROCESS, 
    S.MACHINE, S.PROGRAM, S.TYPE, SW.EVENT, SW.STATE, SW.WAIT_CLASS, SW.WAIT_TIME, SW.SECONDS_IN_WAIT
FROM V$SESSION S, V$SESSION_WAIT SW
WHERE S.SID = SW.SID
AND S.PROGRAM LIKE 'frmweb@AMI-LIVE-APP-01%';

-- ============= FINDING SESSION LOCK 3 ==============--
SELECT
(SELECT USERNAME FROM V$SESSION WHERE SID=A.SID) BLOCKER, A.SID "BLOCKER_ID", (SELECT SERIAL# FROM V$SESSION WHERE SID=A.SID) "BLOCKER_SERIAL",
' IS BLOCKING ' AS ACTION_TYPE,
(SELECT USERNAME FROM V$SESSION WHERE SID=B.SID) BLOCKEE, B.SID "BLOCKEE_ID", (SELECT SERIAL# FROM V$SESSION WHERE SID=B.SID) "BLOCKEE_SERIAL"
FROM V$LOCK A, V$LOCK B
WHERE A.BLOCK = 1 AND B.REQUEST > 0 AND A.ID1=B.ID1 AND A.ID2=B.ID2;

ALTER SYSTEM KILL SESSION '472,44728' IMMEDIATE;