-- ========== SEARCH ACCOUNTS ==========--
SELECT SFC_CODE,SFC_LEVEL,SFC_USERNAME,SFC_PASSWORD,SFC_SURNAME,SFC_REPORTING_CODE,SFC_UGP_GROUP_CODE,DMS_USR_ID
FROM SM_M_SALES_FORCE WHERE SFC_USERNAME IS NOT NULL ORDER BY 1;

-- ========== SEARCH ACCOUNT BY NAME ==========--
SELECT SFC_CODE,SFC_LEVEL,SFC_USERNAME,SFC_PASSWORD,SFC_SURNAME,SFC_REPORTING_CODE,SFC_UGP_GROUP_CODE,DMS_USR_ID,SFC_UGP_GROUP_CODE
FROM SM_M_SALES_FORCE WHERE SFC_USERNAME LIKE '%&USERNAME%' ORDER BY 1;

-- ========== SEARCH ACCOUNT BY CODE ==========--
SELECT SFC_CODE,SFC_LEVEL,SFC_USERNAME,SFC_PASSWORD,SFC_SURNAME,SFC_REPORTING_CODE,SFC_UGP_GROUP_CODE,DMS_USR_ID,SFC_UGP_GROUP_CODE
FROM SM_M_SALES_FORCE WHERE SFC_CODE LIKE '%&CODE%' ORDER BY 1;

-- ========== SEARCH USER BY SURNAME(S) ===========--
SELECT SFC_CODE,SFC_LEVEL,SFC_USERNAME,SFC_PASSWORD,SFC_SURNAME,SFC_REPORTING_CODE,SFC_UGP_GROUP_CODE,DMS_USR_ID,SFC_UGP_GROUP_CODE
FROM SM_M_SALES_FORCE WHERE SFC_SURNAME LIKE '%&USERNAME%' ORDER BY 1;
