-- CLEAR VIEW --
EXEC PK_STAT_REPORTS.PR_DEL_X_DATA;

EXEC PK_STAT_REPORTS.PR_POP_X_DATA('01-JUN-2018', '15-JUN-2018');

EXEC PK_STAT_REPORTS.PR_POP_X_DATA_RC_DATE('01-MAY-2018', '30-MAY-2018');

EXEC PK_STAT_REPORTS.PR_POP_X_DATA_RC_DATE('01-JUN-2018', (SYSDATE - 1));

-- exec pk_stat_reports.pr_pop_x_data('01-DEC-2017', to_char(SYSDATE, 'DD-MON-YYYY'));

-- exec pk_stat_reports.pr_pop_x_data('01-JUN-2018', SYSDATE);

SELECT * FROM VW_FFI_DATA;

SELECT * FROM VW_FFI_MONTHLY;

SELECT * FROM VW_MCC_DATA;

SELECT * FROM VW_MCP_DATA;

SELECT * FROM VW_MCH_DATA;

SELECT * FROM VW_MFC_DATA;

SELECT * FROM VW_MFP_DATA;

SELECT * FROM VW_LHI_DATA;

SELECT * FROM VW_LHI_DETAIL;