CREATE OR REPLACE FORCE EDITIONABLE VIEW "SICL"."POL_RISK_INFO" (
	"POL_PRD_CODE", 
	"POL_POLICY_NO", 
	"POL_ENDORSEMENT_NO", 
	"POL_PERIOD_FROM", 
	"POL_PERIOD_TO", 
	"POL_TRANS_EFFECT_DATE", 
	"PRS_NAME", 
	"PIN_DESCRIPTION", 
	"INFO_VALUE"
) AS 
SELECT 
	UW_X_POLICIES.POL_PRD_CODE, 
	UW_X_POLICIES.POL_POLICY_NO, 
	UW_X_POLICIES.POL_ENDORSEMENT_NO, 
	UW_X_POLICIES.POL_PERIOD_FROM, 
	UW_X_POLICIES.POL_PERIOD_TO, 
	NVL(UW_X_POLICIES.POL_LAST_ENDORSED_DATE, UW_X_POLICIES.POL_PERIOD_FROM) POL_TRANS_EFFECT_DATE, 
	UW_X_POL_RISKS.PRS_NAME, 
	UW_X_POL_INFORMATION.PIN_DESCRIPTION,
	 (CASE
		  WHEN UW_M_PROD_INFORMATION.PIF_RFT_CODE IS NOT NULL
		  THEN
			  PK_CM_R_REFERENCE_TWO.FN_GET_DESCRIPTION ( UW_M_PROD_INFORMATION.PIF_RFT_CODE, PIN_CHAR_VALUE )
		  ELSE
			  NVL ( UW_X_POL_INFORMATION.PIN_CHAR_VALUE, NVL ( TO_CHAR ( UW_X_POL_INFORMATION.PIN_NUMBER_VALUE ), TO_CHAR ( UW_X_POL_INFORMATION.PIN_DATE_VALUE ) ) )
	  END) INFO_VALUE
FROM   
	UW_X_POLICIES,
	UW_X_POL_RISKS,
	UW_X_POL_INFORMATION,
	UW_M_PROD_INFORMATION
WHERE   
	UW_X_POL_INFORMATION.PIN_PIF_SEQ_NO = UW_M_PROD_INFORMATION.PIF_SEQ_NO
	AND UW_X_POL_INFORMATION.PIN_PIF_PRD_CODE = UW_M_PROD_INFORMATION.PIF_PRD_CODE
	AND UW_X_POL_RISKS.PRS_SEQ_NO = UW_X_POL_INFORMATION.PIN_PRS_SEQ_NO
	AND UW_X_POLICIES.POL_SEQ_NO = UW_X_POL_RISKS.PRS_PLC_POL_SEQ_NO
ORDER BY 
	UW_X_POLICIES.POL_POLICY_NO ASC, 
	NVL( UW_X_POLICIES.POL_LAST_ENDORSED_DATE, UW_X_POLICIES.POL_PERIOD_FROM ) ASC, 
	UW_X_POL_RISKS.PRS_R_SEQ ASC,  
	UW_M_PROD_INFORMATION.PIF_I_SEQ ASC;
