EXEC PK_STAT_REPORTS.PR_DEL_X_DATA;

EXEC PK_STAT_REPORTS.PR_POP_X_DATA_POLICY('AMI/YGN/LHI/18000013');  /* wkpolicyno */

-- SELECT * FROM LIFE_DATA

-- SELECT * FROM LIFE_DATA WHERE POL_AUTHORIZED_DATE = (SELECT MAX(POL_AUTHORIZED_DATE) FROM LIFE_DATA);

SELECT * FROM VW_LIFE_DATA;