EXEC PK_STAT_REPORTS.PR_DEL_X_DATA;

EXEC PK_STAT_REPORTS.PR_POP_X_DATA_POLICY('AMI/YGN/LHI/18000001');  --wkpolicyno

SELECT * FROM LIFE_DATA;

DESC LIFE_DATA;

SELECT * FROM UW_T_POLICIES WHERE POL_POLICY_NO LIKE '%LHI%';

SELECT 
    POL_POLICY_NO "POLICY_NO", CUS_INDV_SURNAME "USERNAME", ADR_LOC_DESCRIPTION "ADDRESS", PRS_NIC_NO "NIC", POL_PERIOD_FROM "PERIOD_FROM", 
    POL_PERIOD_TO "PERIOD_TO", BASIC_COVER, ACCIDENT_DEATH, CANCER, SURGICAL, 
    DISABILITY, DISEASE, MISCARRIAGE, COMMISSION, BASIC, 
    ADDITIONAL_UNITS "ADDITIONAL", OPTION_1_UNITS "OPT1", OPTION_2_UNITS "OPT2", INT_INITIMATE_DT "INITIMATE_DATE", INT_CLAIMED_AMT "CLAIMED_AMT", 
    INT_PRS_NAME, RAM_PAYABLE, RAM_CLAIMED 
FROM LIFE_DATA;