/** GENERIC SCRIPTS FOR POPULATING DATA **/

EXEC PK_STAT_REPORTS.PR_DEL_X_DATA;

EXEC PK_STAT_REPORTS.PR_POP_X_DATA('01-AUG-2018', '31-AUG-2018');

EXEC PK_STAT_REPORTS.PR_POP_X_DATA_POLICY('AMI/YGN/LHI/17000415');  /* wkpolicyno */

/** RENEWAL SCRIPTS FOR POPULATING DATA **/

EXEC PK_STAT_REPORTS.PR_POP_X_DATA_LIFE_REN_NOTICE('01-AUG-2018', '31-AUG-2018');

/** VIEWS FOR HEALTH APPLICATION **/

SELECT * FROM LIFE_DATA;        -- GENERAL VIEW FOR LIFE DATA

SELECT * FROM VW_LIFE_DATA;     -- CUSTOMIZED VIEW FOR LIFE DATA